services:
  reactaws:
    build:
      context: .
      dockerfile: ''
    x-cnc:
      type: frontend
      build: yarn dev
      url_path: ''
      assets_path: dis
    x-coherence:
      track_branch_name: main